# Generated by Django 3.1.4 on 2021-01-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Tuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=260)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=260)),
                ('subject', models.CharField(max_length=260)),
                ('message', models.TextField()),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
